import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { 
  CheckCircle, 
  Circle, 
  Droplets, 
  Umbrella, 
  SunMedium, 
  Flame, 
  ShieldAlert, 
  Sparkles, 
  Sprout, 
  Wind, 
  Shirt, 
  Award, 
  Plus, 
  X, 
  PartyPopper,
  CalendarCheck,
  Zap,
  Heart,
  Compass,
  Briefcase,
  Shield,
  Filter,
  Layers
} from 'lucide-react';

interface WeatherData {
  location: {
    name: string;
    country: string;
    region: string;
    localtime: string;
  };
  current: {
    temp_c: number;
    condition: {
      text: string;
      icon: string;
      code: number;
    };
    wind_kph: number;
    precip_mm: number;
    humidity: number;
    feelslike_c: number;
    uv?: number;
    air_quality?: {
      "us-epa-index": number;
    };
  };
}

export type HabitGroupCategory = 'Health' | 'Adventure' | 'Productivity' | 'Safety';

interface HabitItem {
  id: string;
  title: string;
  description: string;
  groupCategory: HabitGroupCategory;
  categoryTag?: string;
  iconName: string;
  isAutoGenerated?: boolean;
}

interface WeatherHabitsSectionProps {
  weatherData: WeatherData | null;
  userName?: string;
}

export const WeatherHabitsSection: React.FC<WeatherHabitsSectionProps> = ({ weatherData, userName }) => {
  const [completedIds, setCompletedIds] = useState<string[]>([]);
  const [customHabits, setCustomHabits] = useState<HabitItem[]>([]);
  const [newHabitText, setNewHabitText] = useState('');
  const [newHabitCategory, setNewHabitCategory] = useState<HabitGroupCategory>('Health');
  const [selectedFilter, setSelectedFilter] = useState<string>('All');
  const [showAddModal, setShowAddModal] = useState(false);

  // Derive location and date key for localStorage persistence
  const locationName = weatherData?.location?.name || 'Default';
  const todayStr = new Date().toISOString().split('T')[0];
  const storageKey = `weather_habits_${todayStr}_${locationName.replace(/\s+/g, '_')}`;

  // Load completed state and custom habits on location/date change
  useEffect(() => {
    try {
      const saved = localStorage.getItem(storageKey);
      if (saved) {
        const parsed = JSON.parse(saved);
        setCompletedIds(parsed.completedIds || []);
        setCustomHabits(parsed.customHabits || []);
      } else {
        setCompletedIds([]);
        setCustomHabits([]);
      }
    } catch (e) {
      console.error('Error loading habit data:', e);
    }
  }, [storageKey]);

  // Save to localStorage
  const saveState = (updatedCompleted: string[], updatedCustom: HabitItem[]) => {
    try {
      localStorage.setItem(storageKey, JSON.stringify({
        completedIds: updatedCompleted,
        customHabits: updatedCustom,
      }));
    } catch (e) {
      console.error('Error saving habit data:', e);
    }
  };

  // Generate dynamic habits from current weather
  const generateDynamicHabits = (): HabitItem[] => {
    const habits: HabitItem[] = [];

    if (!weatherData) {
      return [
        {
          id: 'default-water',
          title: 'Hydration Target: Drink 2L Water',
          description: 'Keep your body hydrated throughout the day.',
          groupCategory: 'Health',
          categoryTag: 'Hydration',
          iconName: 'Droplets',
          isAutoGenerated: true,
        },
        {
          id: 'default-walk',
          title: 'Daily Movement: 20-min Walk',
          description: 'Get active and clear your mind outdoors.',
          groupCategory: 'Adventure',
          categoryTag: 'Outdoor',
          iconName: 'Sprout',
          isAutoGenerated: true,
        },
        {
          id: 'default-focus',
          title: '60-Min Focused Deep Work Session',
          description: 'Set clear priorities and work in distraction-free sprints.',
          groupCategory: 'Productivity',
          categoryTag: 'Focus',
          iconName: 'Briefcase',
          isAutoGenerated: true,
        },
        {
          id: 'default-stretch',
          title: 'Mindful Breathing & Posture Reset',
          description: 'Take 5 minutes for deep breathing and posture alignment.',
          groupCategory: 'Health',
          categoryTag: 'Wellness',
          iconName: 'Sparkles',
          isAutoGenerated: true,
        }
      ];
    }

    const { temp_c, condition, precip_mm, humidity, wind_kph, uv = 0, air_quality } = weatherData.current;
    const condText = condition.text.toLowerCase();
    const isRaining = precip_mm > 0 || condText.includes('rain') || condText.includes('drizzle') || condText.includes('thunder') || condText.includes('shower');
    const isSnowing = condText.includes('snow') || condText.includes('sleet') || condText.includes('ice');

    // --- HEALTH CATEGORY ---
    if (temp_c >= 25) {
      habits.push({
        id: 'habit-hydration-heat',
        title: 'Drink 2.5L Water Today',
        description: `High temp of ${Math.round(temp_c)}°C increases fluid loss. Stay hydrated!`,
        groupCategory: 'Health',
        categoryTag: 'Hydration',
        iconName: 'Droplets',
        isAutoGenerated: true,
      });
    } else {
      habits.push({
        id: 'habit-hydration-normal',
        title: 'Drink 2L Water Today',
        description: 'Maintain steady hydration throughout your daily routine.',
        groupCategory: 'Health',
        categoryTag: 'Hydration',
        iconName: 'Droplets',
        isAutoGenerated: true,
      });
    }

    if (uv >= 3) {
      habits.push({
        id: 'habit-uv-protection',
        title: uv >= 6 ? 'Apply SPF 50+ Sunscreen & Sunglasses' : 'Apply Daily Sunscreen & Eye Protection',
        description: `UV index is ${uv}. Shield exposed skin from UV radiation.`,
        groupCategory: 'Health',
        categoryTag: 'Skin Care',
        iconName: 'SunMedium',
        isAutoGenerated: true,
      });
    }

    if (humidity < 35) {
      habits.push({
        id: 'habit-humidity-low',
        title: 'Hydrate Skin & Use Lip Balm',
        description: `Low humidity (${humidity}%) dries out skin and nasal passages.`,
        groupCategory: 'Health',
        categoryTag: 'Wellness',
        iconName: 'Sparkles',
        isAutoGenerated: true,
      });
    }

    // --- PRODUCTIVITY CATEGORY ---
    if (isRaining || isSnowing || temp_c > 35 || temp_c < 5) {
      habits.push({
        id: 'habit-cozy-productivity',
        title: 'Cozy Indoor Deep-Work Sprint (90 min)',
        description: 'Weather is intense outdoors. Perfect atmosphere for uninterrupted focus.',
        groupCategory: 'Productivity',
        categoryTag: 'Focus',
        iconName: 'Briefcase',
        isAutoGenerated: true,
      });
    } else {
      habits.push({
        id: 'habit-outdoor-planning',
        title: 'Morning Sunlit Task Planning',
        description: 'Spend 10 minutes planning your top 3 goals under natural sunlight.',
        groupCategory: 'Productivity',
        categoryTag: 'Planning',
        iconName: 'Briefcase',
        isAutoGenerated: true,
      });
    }

    habits.push({
      id: 'habit-hourly-break',
      title: 'Hourly Movement & Hydration Standup',
      description: 'Take a 2-minute break every hour to stretch and drink a glass of water.',
      groupCategory: 'Productivity',
      categoryTag: 'Workflow',
      iconName: 'Zap',
      isAutoGenerated: true,
    });

    // --- ADVENTURE CATEGORY ---
    if (!isRaining && !isSnowing && temp_c >= 12 && temp_c <= 30) {
      habits.push({
        id: 'habit-outdoor-walk',
        title: '20-Minute Refreshing Outdoor Walk / Jog',
        description: `Great weather (${condition.text}, ${Math.round(temp_c)}°C). Enjoy nature & fresh air!`,
        groupCategory: 'Adventure',
        categoryTag: 'Exploration',
        iconName: 'Sprout',
        isAutoGenerated: true,
      });
    } else if (isRaining) {
      habits.push({
        id: 'habit-rain-adventure',
        title: 'Rainy Day Exploration / Warm Indoor Cafe Walk',
        description: 'Rain is falling. Grab a sturdy umbrella or explore a local indoor market.',
        groupCategory: 'Adventure',
        categoryTag: 'Urban Hike',
        iconName: 'Compass',
        isAutoGenerated: true,
      });
    } else if (isSnowing) {
      habits.push({
        id: 'habit-snow-adventure',
        title: 'Crisp Snow Walk with Insulated Boots',
        description: 'Bundle up warm and take a brisk walk to enjoy the winter landscape.',
        groupCategory: 'Adventure',
        categoryTag: 'Winter Hike',
        iconName: 'Compass',
        isAutoGenerated: true,
      });
    }

    // --- SAFETY CATEGORY ---
    if (isRaining) {
      habits.push({
        id: 'habit-rain-gear',
        title: 'Rain Shield: Carry Waterproof Gear',
        description: `Active rainfall (${precip_mm}mm). Keep umbrella and waterproof shoes handy.`,
        groupCategory: 'Safety',
        categoryTag: 'Weather Alert',
        iconName: 'Umbrella',
        isAutoGenerated: true,
      });
    }

    const aqiIndex = air_quality?.["us-epa-index"] || 1;
    if (aqiIndex >= 3) {
      habits.push({
        id: 'habit-aqi-safety',
        title: 'AQI Warning: Wear N95 Mask Outdoors',
        description: `Air Quality Index is elevated (Level ${aqiIndex}). Limit intense cardio outdoors.`,
        groupCategory: 'Safety',
        categoryTag: 'Air Quality',
        iconName: 'ShieldAlert',
        isAutoGenerated: true,
      });
    }

    if (temp_c < 12) {
      habits.push({
        id: 'habit-cold-warmth',
        title: temp_c < 5 ? 'Thermal Layering & Gloves' : 'Wear Warm Jacket & Drink Hot Tea',
        description: `Chilly temp of ${Math.round(temp_c)}°C. Preserve body heat and avoid drafts.`,
        groupCategory: 'Safety',
        categoryTag: 'Temperature',
        iconName: temp_c < 5 ? 'Shirt' : 'Flame',
        isAutoGenerated: true,
      });
    }

    if (wind_kph > 30) {
      habits.push({
        id: 'habit-high-wind',
        title: 'Windbreaker & Secure Loose Outdoor Items',
        description: `Strong gusts (${wind_kph} km/h). Shield eyes from flying dust and debris.`,
        groupCategory: 'Safety',
        categoryTag: 'Wind Alert',
        iconName: 'Wind',
        isAutoGenerated: true,
      });
    }

    return habits;
  };

  const autoHabits = generateDynamicHabits();
  const allHabits = [...autoHabits, ...customHabits];

  // Filter habits according to selected tab
  const filteredHabits = selectedFilter === 'All'
    ? allHabits
    : allHabits.filter(h => h.groupCategory === selectedFilter);

  const toggleHabit = (id: string) => {
    const updated = completedIds.includes(id)
      ? completedIds.filter(item => item !== id)
      : [...completedIds, id];
    setCompletedIds(updated);
    saveState(updated, customHabits);
  };

  const addCustomHabit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!newHabitText.trim()) return;

    const newItem: HabitItem = {
      id: `custom-${Date.now()}`,
      title: newHabitText.trim(),
      description: 'Personal custom habit goal for today.',
      groupCategory: newHabitCategory,
      categoryTag: 'Custom Goal',
      iconName: newHabitCategory === 'Health' ? 'Heart' : newHabitCategory === 'Adventure' ? 'Compass' : newHabitCategory === 'Productivity' ? 'Briefcase' : 'Shield',
      isAutoGenerated: false,
    };

    const updatedCustom = [...customHabits, newItem];
    setCustomHabits(updatedCustom);
    setNewHabitText('');
    setShowAddModal(false);
    saveState(completedIds, updatedCustom);
  };

  const deleteCustomHabit = (id: string, e: React.MouseEvent) => {
    e.stopPropagation();
    const updatedCustom = customHabits.filter(h => h.id !== id);
    const updatedCompleted = completedIds.filter(cId => cId !== id);
    setCustomHabits(updatedCustom);
    setCompletedIds(updatedCompleted);
    saveState(updatedCompleted, updatedCustom);
  };

  // Helper to render icon dynamically
  const renderHabitIcon = (iconName: string) => {
    switch (iconName) {
      case 'Droplets': return <Droplets className="w-5 h-5 text-blue-400" />;
      case 'Umbrella': return <Umbrella className="w-5 h-5 text-indigo-400" />;
      case 'SunMedium': return <SunMedium className="w-5 h-5 text-amber-400" />;
      case 'Flame': return <Flame className="w-5 h-5 text-orange-400" />;
      case 'Shirt': return <Shirt className="w-5 h-5 text-sky-400" />;
      case 'ShieldAlert': return <ShieldAlert className="w-5 h-5 text-rose-400" />;
      case 'Sparkles': return <Sparkles className="w-5 h-5 text-purple-400" />;
      case 'Sprout': return <Sprout className="w-5 h-5 text-emerald-400" />;
      case 'Wind': return <Wind className="w-5 h-5 text-cyan-400" />;
      case 'Heart': return <Heart className="w-5 h-5 text-emerald-400" />;
      case 'Compass': return <Compass className="w-5 h-5 text-amber-400" />;
      case 'Briefcase': return <Briefcase className="w-5 h-5 text-blue-400" />;
      case 'Shield': return <Shield className="w-5 h-5 text-purple-400" />;
      default: return <Zap className="w-5 h-5 text-blue-400" />;
    }
  };

  // Render badge style for category
  const renderCategoryBadge = (group: HabitGroupCategory, tag?: string) => {
    switch (group) {
      case 'Health':
        return (
          <span className="inline-flex items-center gap-1 text-[10px] font-semibold tracking-wide uppercase px-2 py-0.5 rounded-md bg-emerald-500/15 text-emerald-300 border border-emerald-500/30">
            <Heart className="w-3 h-3 text-emerald-400" /> {tag || 'Health'}
          </span>
        );
      case 'Adventure':
        return (
          <span className="inline-flex items-center gap-1 text-[10px] font-semibold tracking-wide uppercase px-2 py-0.5 rounded-md bg-amber-500/15 text-amber-300 border border-amber-500/30">
            <Compass className="w-3 h-3 text-amber-400" /> {tag || 'Adventure'}
          </span>
        );
      case 'Productivity':
        return (
          <span className="inline-flex items-center gap-1 text-[10px] font-semibold tracking-wide uppercase px-2 py-0.5 rounded-md bg-blue-500/15 text-blue-300 border border-blue-500/30">
            <Briefcase className="w-3 h-3 text-blue-400" /> {tag || 'Productivity'}
          </span>
        );
      case 'Safety':
        return (
          <span className="inline-flex items-center gap-1 text-[10px] font-semibold tracking-wide uppercase px-2 py-0.5 rounded-md bg-purple-500/15 text-purple-300 border border-purple-500/30">
            <Shield className="w-3 h-3 text-purple-400" /> {tag || 'Safety'}
          </span>
        );
      default:
        return null;
    }
  };

  const totalCount = allHabits.length;
  const completedCount = allHabits.filter(h => completedIds.includes(h.id)).length;
  const progressPercent = totalCount > 0 ? Math.round((completedCount / totalCount) * 100) : 0;
  const isAllDone = totalCount > 0 && completedCount === totalCount;

  // Filter Categories setup
  const filterCategories: { id: string; label: string; icon: React.ReactNode }[] = [
    { id: 'All', label: 'All Goals', icon: <Layers className="w-3.5 h-3.5" /> },
    { id: 'Health', label: 'Health', icon: <Heart className="w-3.5 h-3.5 text-emerald-400" /> },
    { id: 'Adventure', label: 'Adventure', icon: <Compass className="w-3.5 h-3.5 text-amber-400" /> },
    { id: 'Productivity', label: 'Productivity', icon: <Briefcase className="w-3.5 h-3.5 text-blue-400" /> },
    { id: 'Safety', label: 'Safety', icon: <Shield className="w-3.5 h-3.5 text-purple-400" /> },
  ];

  return (
    <div className="w-full mt-8 mb-6">
      {/* Section Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 mb-6 px-2">
        <div className="flex items-center space-x-3">
          <div className="p-2.5 bg-blue-500/20 border border-blue-400/30 rounded-2xl flex items-center justify-center">
            <CalendarCheck className="text-blue-300 w-6 h-6" />
          </div>
          <div>
            <h3 className="font-display text-2xl font-semibold tracking-tight text-white drop-shadow-md">
              Weather-Based Daily Habits
            </h3>
            <p className="text-xs sm:text-sm text-blue-200/70">
              Targeted suggestions for today's weather in {locationName}
            </p>
          </div>
        </div>

        <button
          onClick={() => setShowAddModal(true)}
          className="self-start sm:self-auto flex items-center gap-2 px-4 py-2.5 bg-blue-600/80 hover:bg-blue-500 text-white rounded-xl text-xs sm:text-sm font-medium border border-blue-400/30 transition-all shadow-md cursor-pointer hover:shadow-lg"
        >
          <Plus className="w-4 h-4" /> Add Custom Goal
        </button>
      </div>

      <div className="w-full bg-white/5 backdrop-blur-xl border border-white/10 rounded-[2rem] p-4 sm:p-6 shadow-xl">
        {/* Progress Bar Header */}
        <div className="mb-6 bg-black/20 border border-white/10 rounded-2xl p-4 sm:p-5 flex flex-col gap-3">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <Award className={`w-5 h-5 ${isAllDone ? 'text-amber-400 animate-bounce' : 'text-blue-400'}`} />
              <span className="text-sm font-semibold text-white">
                {isAllDone ? '🎉 Fantastic Job! All Weather Goals Completed!' : 'Today\'s Progress'}
              </span>
            </div>
            <span className="text-xs sm:text-sm font-bold text-blue-300 bg-blue-500/20 px-3 py-1 rounded-full border border-blue-400/30">
              {completedCount} of {totalCount} Completed ({progressPercent}%)
            </span>
          </div>

          <div className="w-full h-3 bg-black/40 rounded-full overflow-hidden p-0.5 border border-white/5 relative">
            <motion.div
              initial={{ width: 0 }}
              animate={{ width: `${progressPercent}%` }}
              transition={{ duration: 0.6, ease: 'easeOut' }}
              className={`h-full rounded-full transition-all ${
                isAllDone 
                  ? 'bg-gradient-to-r from-emerald-400 via-amber-300 to-emerald-400 shadow-[0_0_12px_rgba(52,211,153,0.8)]' 
                  : 'bg-gradient-to-r from-blue-500 to-indigo-400'
              }`}
            />
          </div>

          {isAllDone && (
            <motion.div 
              initial={{ opacity: 0, scale: 0.9 }}
              animate={{ opacity: 1, scale: 1 }}
              className="flex items-center gap-2 text-xs text-amber-300/90 font-medium bg-amber-500/10 border border-amber-400/20 rounded-xl p-2.5 mt-1"
            >
              <PartyPopper className="w-4 h-4 text-amber-400 shrink-0" />
              <span>You have fulfilled all weather recommendations for today. Stay safe and productive!</span>
            </motion.div>
          )}
        </div>

        {/* Category Filter Toggles */}
        <div className="mb-6 flex items-center gap-2 overflow-x-auto pb-1 scrollbar-none">
          <div className="flex items-center gap-1 text-xs font-semibold text-blue-200/60 uppercase tracking-wider mr-1 shrink-0">
            <Filter className="w-3.5 h-3.5" /> Filter:
          </div>
          {filterCategories.map(cat => {
            const isActive = selectedFilter === cat.id;
            const count = cat.id === 'All' 
              ? allHabits.length 
              : allHabits.filter(h => h.groupCategory === cat.id).length;

            return (
              <button
                key={cat.id}
                onClick={() => setSelectedFilter(cat.id)}
                className={`flex items-center gap-2 px-3.5 py-1.5 rounded-xl text-xs font-medium border transition-all cursor-pointer shrink-0 ${
                  isActive
                    ? 'bg-blue-600/90 text-white border-blue-400/50 shadow-md scale-105'
                    : 'bg-black/30 hover:bg-white/10 text-white/70 border-white/10 hover:border-white/20'
                }`}
              >
                {cat.icon}
                <span>{cat.label}</span>
                <span className={`px-1.5 py-0.2 rounded-full text-[10px] ${
                  isActive ? 'bg-white/20 text-white' : 'bg-white/10 text-white/60'
                }`}>
                  {count}
                </span>
              </button>
            );
          })}
        </div>

        {/* Habit Cards Grid */}
        {filteredHabits.length === 0 ? (
          <div className="text-center py-10 px-4 bg-black/20 rounded-2xl border border-white/5">
            <p className="text-sm text-blue-200/60">No habits found in the "{selectedFilter}" category for today.</p>
            <button
              onClick={() => setSelectedFilter('All')}
              className="mt-3 text-xs text-blue-400 hover:underline font-medium"
            >
              Show all categories
            </button>
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 gap-3.5">
            {filteredHabits.map((habit, index) => {
              const isDone = completedIds.includes(habit.id);
              return (
                <motion.div
                  key={habit.id}
                  initial={{ opacity: 0, y: 15 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.3, delay: index * 0.04 }}
                  onClick={() => toggleHabit(habit.id)}
                  className={`group relative p-4 rounded-2xl border transition-all duration-300 cursor-pointer flex items-start gap-3.5 select-none ${
                    isDone
                      ? 'bg-emerald-950/20 border-emerald-500/40 shadow-[0_0_15px_rgba(16,185,129,0.1)]'
                      : 'bg-white/5 hover:bg-white/10 border-white/10 hover:border-white/20'
                  }`}
                >
                  {/* Custom delete button */}
                  {!habit.isAutoGenerated && (
                    <button
                      onClick={(e) => deleteCustomHabit(habit.id, e)}
                      title="Delete Custom Goal"
                      className="absolute top-2.5 right-2.5 p-1 rounded-lg text-white/30 hover:text-red-400 hover:bg-white/10 transition-colors z-10"
                    >
                      <X className="w-3.5 h-3.5" />
                    </button>
                  )}

                  {/* Confetti & Checkmark Burst Animations */}
                  <AnimatePresence>
                    {isDone && (
                      <React.Fragment key={`confetti-${habit.id}`}>
                        {/* Expanding Ripple Ring around checkbox */}
                        <motion.div
                          initial={{ scale: 0.5, opacity: 0.9 }}
                          animate={{ scale: 2.2, opacity: 0 }}
                          exit={{ opacity: 0 }}
                          transition={{ duration: 0.5, ease: "easeOut" }}
                          className="absolute left-[1.65rem] top-7 -translate-x-1/2 -translate-y-1/2 w-7 h-7 rounded-full border-2 border-emerald-400 pointer-events-none z-10"
                        />

                        {/* Radial Confetti Particles Burst */}
                        {[...Array(12)].map((_, i) => {
                          const angle = (i / 12) * (2 * Math.PI);
                          const distance = 20 + (i % 3) * 12; // 20px - 44px radial burst
                          const xTarget = Math.cos(angle) * distance;
                          const yTarget = Math.sin(angle) * distance;
                          const particleColors = ['#34d399', '#f59e0b', '#60a5fa', '#a78bfa', '#f472b6', '#10b981'];
                          const color = particleColors[i % particleColors.length];

                          return (
                            <motion.span
                              key={`p-${habit.id}-${i}`}
                              initial={{ x: 0, y: 0, scale: 0, opacity: 1, rotate: 0 }}
                              animate={{ 
                                x: xTarget, 
                                y: yTarget, 
                                scale: [0, 1.4, 0], 
                                opacity: [1, 1, 0],
                                rotate: (i % 2 === 0 ? 1 : -1) * 220 
                              }}
                              transition={{ duration: 0.65, ease: "easeOut", delay: i * 0.015 }}
                              style={{ backgroundColor: color }}
                              className="absolute left-[1.65rem] top-7 -translate-x-1/2 -translate-y-1/2 w-1.5 h-1.5 rounded-full pointer-events-none z-20 shadow-sm"
                            />
                          );
                        })}

                        {/* Floating "+1 Goal Completed!" Toast Sparkle Badge */}
                        <motion.div
                          initial={{ y: 0, opacity: 1, scale: 0.7 }}
                          animate={{ y: -26, opacity: 0, scale: 1.05 }}
                          exit={{ opacity: 0 }}
                          transition={{ duration: 0.85, ease: "easeOut" }}
                          className="absolute left-10 top-0 -translate-x-1/2 text-[10px] font-bold text-emerald-200 bg-emerald-950/90 border border-emerald-400/40 px-2.5 py-0.5 rounded-full pointer-events-none z-30 shadow-lg flex items-center gap-1.5 whitespace-nowrap"
                        >
                          <Sparkles className="w-3 h-3 text-amber-300 animate-spin" /> Completed! ✨
                        </motion.div>
                      </React.Fragment>
                    )}
                  </AnimatePresence>

                  {/* Checkbox Icon */}
                  <div className="mt-0.5 shrink-0 relative z-10">
                    {isDone ? (
                      <motion.div
                        initial={{ scale: 0.2, rotate: -25 }}
                        animate={{ scale: 1, rotate: 0 }}
                        transition={{ type: "spring", stiffness: 500, damping: 15 }}
                      >
                        <CheckCircle className="w-6 h-6 text-emerald-400 fill-emerald-400/20 drop-shadow-[0_0_8px_rgba(52,211,153,0.6)]" />
                      </motion.div>
                    ) : (
                      <Circle className="w-6 h-6 text-white/30 group-hover:text-blue-400 transition-colors" />
                    )}
                  </div>

                  {/* Icon Badge */}
                  <div className={`p-2 rounded-xl shrink-0 ${isDone ? 'bg-emerald-500/10 border border-emerald-500/20' : 'bg-white/10 border border-white/10'}`}>
                    {renderHabitIcon(habit.iconName)}
                  </div>

                  {/* Text Content & Category Badge */}
                  <div className="flex-1 min-w-0 pr-4">
                    <div className="flex items-center gap-2 mb-1 flex-wrap">
                      {renderCategoryBadge(habit.groupCategory, habit.categoryTag)}
                    </div>
                    <h4 className={`text-sm font-semibold transition-all ${
                      isDone ? 'line-through text-white/50' : 'text-white group-hover:text-blue-200'
                    }`}>
                      {habit.title}
                    </h4>
                    <p className={`text-xs mt-1 leading-relaxed ${
                      isDone ? 'text-white/40' : 'text-blue-100/70'
                    }`}>
                      {habit.description}
                    </p>
                  </div>
                </motion.div>
              );
            })}
          </div>
        )}
      </div>

      {/* Modal for Adding Custom Habit */}
      <AnimatePresence>
        {showAddModal && (
          <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-md">
            <motion.div
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.95 }}
              className="w-full max-w-md bg-slate-900 border border-white/20 rounded-2xl p-6 shadow-2xl relative"
            >
              <button
                onClick={() => setShowAddModal(false)}
                className="absolute top-4 right-4 text-white/50 hover:text-white p-1 rounded-lg hover:bg-white/10 transition-colors"
              >
                <X className="w-5 h-5" />
              </button>

              <h3 className="text-lg font-bold text-white mb-1 flex items-center gap-2">
                <Plus className="w-5 h-5 text-blue-400" /> Add Custom Daily Habit
              </h3>
              <p className="text-xs text-blue-200/70 mb-4">
                Set a custom goal to track alongside your weather-based habits today.
              </p>

              <form onSubmit={addCustomHabit} className="space-y-4">
                <div>
                  <label className="block text-xs font-medium text-white/80 mb-1">
                    Goal / Habit Description
                  </label>
                  <input
                    type="text"
                    value={newHabitText}
                    onChange={(e) => setNewHabitText(e.target.value)}
                    placeholder="e.g. Carry 1.5L thermal flask, Read 15 mins..."
                    required
                    autoFocus
                    className="w-full bg-white/10 border border-white/20 rounded-xl px-3.5 py-2.5 text-sm text-white placeholder-white/40 focus:outline-none focus:ring-2 focus:ring-blue-400/50"
                  />
                </div>

                <div>
                  <label className="block text-xs font-medium text-white/80 mb-1">
                    Category Tag
                  </label>
                  <div className="grid grid-cols-2 gap-2">
                    {(['Health', 'Adventure', 'Productivity', 'Safety'] as HabitGroupCategory[]).map(cat => (
                      <button
                        key={cat}
                        type="button"
                        onClick={() => setNewHabitCategory(cat)}
                        className={`flex items-center justify-center gap-2 px-3 py-2 rounded-xl text-xs font-medium border transition-all cursor-pointer ${
                          newHabitCategory === cat
                            ? 'bg-blue-600 text-white border-blue-400'
                            : 'bg-white/5 hover:bg-white/10 text-white/70 border-white/10'
                        }`}
                      >
                        {cat === 'Health' && <Heart className="w-3.5 h-3.5 text-emerald-400" />}
                        {cat === 'Adventure' && <Compass className="w-3.5 h-3.5 text-amber-400" />}
                        {cat === 'Productivity' && <Briefcase className="w-3.5 h-3.5 text-blue-400" />}
                        {cat === 'Safety' && <Shield className="w-3.5 h-3.5 text-purple-400" />}
                        {cat}
                      </button>
                    ))}
                  </div>
                </div>

                <div className="flex items-center justify-end gap-2 pt-2">
                  <button
                    type="button"
                    onClick={() => setShowAddModal(false)}
                    className="px-4 py-2 bg-white/10 hover:bg-white/20 text-white rounded-xl text-xs font-medium transition-colors cursor-pointer"
                  >
                    Cancel
                  </button>
                  <button
                    type="submit"
                    className="px-4 py-2 bg-blue-600 hover:bg-blue-500 text-white rounded-xl text-xs font-medium transition-colors shadow-md cursor-pointer"
                  >
                    Save Goal
                  </button>
                </div>
              </form>
            </motion.div>
          </div>
        )}
      </AnimatePresence>
    </div>
  );
};

